spring:
  application:
    name: configservergit

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Poorna-chandra2000/jobaapp-config-server.git
          username: Poorna-chandra2000
          password: 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
          default-label: main
#https://github:
#  com/Poorna-chandra2000/jobaapp-config-server:
#    git:
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true
